/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedPushIndexRouteImport } from './routes/_authenticated/push/index'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn/index'
import { Route as AuthenticatedInstrumentsIndexRouteImport } from './routes/_authenticated/instruments/index'
import { Route as AuthenticatedEquityListsIndexRouteImport } from './routes/_authenticated/equity-lists/index'
import { Route as AuthenticatedEgxHolidaysIndexRouteImport } from './routes/_authenticated/egx-holidays/index'
import { Route as AuthenticatedContactIndexRouteImport } from './routes/_authenticated/contact/index'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements/index'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedWebsitePagesIndexRouteImport } from './routes/_authenticated/website/pages/index'
import { Route as AuthenticatedWebsiteNavigationIndexRouteImport } from './routes/_authenticated/website/navigation/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPushIndexRoute = AuthenticatedPushIndexRouteImport.update({
  id: '/push/',
  path: '/push/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstrumentsIndexRoute =
  AuthenticatedInstrumentsIndexRouteImport.update({
    id: '/instruments/',
    path: '/instruments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquityListsIndexRoute =
  AuthenticatedEquityListsIndexRouteImport.update({
    id: '/equity-lists/',
    path: '/equity-lists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEgxHolidaysIndexRoute =
  AuthenticatedEgxHolidaysIndexRouteImport.update({
    id: '/egx-holidays/',
    path: '/egx-holidays/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactIndexRoute =
  AuthenticatedContactIndexRouteImport.update({
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsitePagesIndexRoute =
  AuthenticatedWebsitePagesIndexRouteImport.update({
    id: '/website/pages/',
    path: '/website/pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteNavigationIndexRoute =
  AuthenticatedWebsiteNavigationIndexRouteImport.update({
    id: '/website/navigation/',
    path: '/website/navigation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/contact/': typeof AuthenticatedContactIndexRoute
  '/egx-holidays/': typeof AuthenticatedEgxHolidaysIndexRoute
  '/equity-lists/': typeof AuthenticatedEquityListsIndexRoute
  '/instruments/': typeof AuthenticatedInstrumentsIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/push/': typeof AuthenticatedPushIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/website/navigation/': typeof AuthenticatedWebsiteNavigationIndexRoute
  '/website/pages/': typeof AuthenticatedWebsitePagesIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
  '/contact': typeof AuthenticatedContactIndexRoute
  '/egx-holidays': typeof AuthenticatedEgxHolidaysIndexRoute
  '/equity-lists': typeof AuthenticatedEquityListsIndexRoute
  '/instruments': typeof AuthenticatedInstrumentsIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/push': typeof AuthenticatedPushIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/website/navigation': typeof AuthenticatedWebsiteNavigationIndexRoute
  '/website/pages': typeof AuthenticatedWebsitePagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/_authenticated/contact/': typeof AuthenticatedContactIndexRoute
  '/_authenticated/egx-holidays/': typeof AuthenticatedEgxHolidaysIndexRoute
  '/_authenticated/equity-lists/': typeof AuthenticatedEquityListsIndexRoute
  '/_authenticated/instruments/': typeof AuthenticatedInstrumentsIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/push/': typeof AuthenticatedPushIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/website/navigation/': typeof AuthenticatedWebsiteNavigationIndexRoute
  '/_authenticated/website/pages/': typeof AuthenticatedWebsitePagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings/integrations'
    | '/activity/'
    | '/announcements/'
    | '/contact/'
    | '/egx-holidays/'
    | '/equity-lists/'
    | '/instruments/'
    | '/learn/'
    | '/push/'
    | '/users/'
    | '/website/navigation/'
    | '/website/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/integrations'
    | '/activity'
    | '/announcements'
    | '/contact'
    | '/egx-holidays'
    | '/equity-lists'
    | '/instruments'
    | '/learn'
    | '/push'
    | '/users'
    | '/website/navigation'
    | '/website/pages'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/activity/'
    | '/_authenticated/announcements/'
    | '/_authenticated/contact/'
    | '/_authenticated/egx-holidays/'
    | '/_authenticated/equity-lists/'
    | '/_authenticated/instruments/'
    | '/_authenticated/learn/'
    | '/_authenticated/push/'
    | '/_authenticated/users/'
    | '/_authenticated/website/navigation/'
    | '/_authenticated/website/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/push/': {
      id: '/_authenticated/push/'
      path: '/push'
      fullPath: '/push/'
      preLoaderRoute: typeof AuthenticatedPushIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instruments/': {
      id: '/_authenticated/instruments/'
      path: '/instruments'
      fullPath: '/instruments/'
      preLoaderRoute: typeof AuthenticatedInstrumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equity-lists/': {
      id: '/_authenticated/equity-lists/'
      path: '/equity-lists'
      fullPath: '/equity-lists/'
      preLoaderRoute: typeof AuthenticatedEquityListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/egx-holidays/': {
      id: '/_authenticated/egx-holidays/'
      path: '/egx-holidays'
      fullPath: '/egx-holidays/'
      preLoaderRoute: typeof AuthenticatedEgxHolidaysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact/': {
      id: '/_authenticated/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof AuthenticatedContactIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/pages/': {
      id: '/_authenticated/website/pages/'
      path: '/website/pages'
      fullPath: '/website/pages/'
      preLoaderRoute: typeof AuthenticatedWebsitePagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/navigation/': {
      id: '/_authenticated/website/navigation/'
      path: '/website/navigation'
      fullPath: '/website/navigation/'
      preLoaderRoute: typeof AuthenticatedWebsiteNavigationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
  AuthenticatedContactIndexRoute: typeof AuthenticatedContactIndexRoute
  AuthenticatedEgxHolidaysIndexRoute: typeof AuthenticatedEgxHolidaysIndexRoute
  AuthenticatedEquityListsIndexRoute: typeof AuthenticatedEquityListsIndexRoute
  AuthenticatedInstrumentsIndexRoute: typeof AuthenticatedInstrumentsIndexRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedPushIndexRoute: typeof AuthenticatedPushIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebsiteNavigationIndexRoute: typeof AuthenticatedWebsiteNavigationIndexRoute
  AuthenticatedWebsitePagesIndexRoute: typeof AuthenticatedWebsitePagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
  AuthenticatedContactIndexRoute: AuthenticatedContactIndexRoute,
  AuthenticatedEgxHolidaysIndexRoute: AuthenticatedEgxHolidaysIndexRoute,
  AuthenticatedEquityListsIndexRoute: AuthenticatedEquityListsIndexRoute,
  AuthenticatedInstrumentsIndexRoute: AuthenticatedInstrumentsIndexRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedPushIndexRoute: AuthenticatedPushIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebsiteNavigationIndexRoute:
    AuthenticatedWebsiteNavigationIndexRoute,
  AuthenticatedWebsitePagesIndexRoute: AuthenticatedWebsitePagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
